version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10

  pre_build:
    commands:
      - npm install

  build:
    commands:
      # Create a hash for staticpkg in PXT to use for building
      - DEPLOY_HASH="$(git rev-parse HEAD)"
      # Build using our build script
      - npm run build
      # It might be cute to put the following in post_build, but unfortunately you have
      # to check for a successful build in that case... (CODEBUILD_BUILD_SUCCEEDING)
      - BRANCH="$(git branch -a --contains HEAD | grep -vF -e '(no branch)' -e 'origin' | head -1 | sed 's/^..//')"
      - echo "On branch $BRANCH (commit/deploy_hash $DEPLOY_HASH)..."
      - if [ "$BRANCH" = develop -o "$BRANCH" = master ]; then deploy=true; else deploy=false; fi

      # cache-control max-age set to 30 days (shouldn't need to invalidate, but just in case...)
      - if $deploy; then aws s3 sync --cache-control 'max-age=2592000' built/packaged/$DEPLOY_HASH "s3://$S3_BUCKET_NAME/$DEPLOY_HASH"; fi

      # Record 'latest' deploy here (potentially allows bucket to select what we want).
      # S3 only supports 301 redirects, so we can fake it server side.
      - DEPLOY_HASH_FILE="$(mktemp)"
      - echo "/$DEPLOY_HASH/index.html?controller=1" > "$DEPLOY_HASH_FILE"
      - if $deploy; then aws s3 cp --content-type 'text/plain' --cache-control 'no-cache' "$DEPLOY_HASH_FILE" "s3://$S3_BUCKET_NAME/latest_deploy_redirect"; fi

# If you have local_cache on, it seems to do some symlink-y stuff here, and tsc seems to get grumpy
# about that (hypothesis).
#cache:
#  paths:
#    - node_modules/**/*
